name: Update GitHub stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: update-github-stats
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun scripts/generate-github-stats.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
          GITHUB_USERNAME: yob-yob

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: update github stats'
          file_pattern: static/data/github-stats.json
          skip_dirty_check: true
          commit_user_name: Github Action (Update Github Stats)
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Github Action (Update Github Stats) <41898282+github-actions[bot]@users.noreply.github.com>
